### ISSUE TITLE
Elizabeth line support

### ISSUE THREAD

**Issue by oliver-bradley-rft** [asabreu/tflstatus#1]
hi - any chance you could support the elizabeth line?
i've tried adding updating the number of lines in line.h and adding lines to display.c but i get a segmentation fault (i am not a coder...)

**Comment by asabreu** [comment]
Sure I'll add this 1st week of September upon my return to work. Thanks for the suggestion.

**Comment by asabreu** [comment]
Added Elizabeth line support in v1.1
